version: '3.8'

services:
  postgres_platform_db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_DB: 'videoplatform'
      POSTGRES_USER: '12345'
      POSTGRES_PASSWORD: '12345'
    ports:
      - '5434:5432'
  postgres_platform_test_db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_DB: 'videoplatform'
      POSTGRES_USER: '12345'
      POSTGRES_PASSWORD: '12345'
    ports:
      - '5435:5432'