###Homepage
GET http://localhost:8080

###API: retrieve 1 channel
GET http://localhost:8080/api/channels/1
Accept: application/json
Content-Type: application/json

###API: retrieve 1 channel (not found)
GET http://localhost:8080/api/channels/90
Accept: application/json
Content-Type: application/json

### API: delete a channel
DELETE http://localhost:8080/api/channels/2
Cookie: JSESSIONID=502C4B861E5DA64AD40A4B0E00FC9459
X-CSRF-TOKEN: Klwnj75EK2ObwHAsu2iuJv0dCbXF8rKFD7bSekYh2J5BY6sYHG0Wvdx9SQa28BIYikWaFc5-JIz9kYWoao60TX4Uu6h5VJIo

### API: delete a video
DELETE http://localhost:8080/api/videos/2
Cookie: JSESSIONID=A70B94512FC9E2EEEA1D531183D1EEB6
X-CSRF-TOKEN:ngIZDIC_wi2JXbVOyF-h7j4SnBGrZRfHwnFadLvso-FXjYg2qzQoPbiK9xSkbYV3-HKV2wYgsSjNBCfqo0NrEY7YlIBhvr0A

### API: delete a channel (not found)
DELETE http://localhost:8080/api/channels/90

###API: retrieve videos of a channel
GET http://localhost:8080/api/channels/1/videos

###API: Creating channel
# @no-redirect
POST http://localhost:8080/api/channels
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=01AED759216BCA55B703E52FCC35CEDE

{
  "name": "The name",
  "date": "2024-03-11",
  "subscribers": 345
}

###API: Creating channel (bad request)
# @no-redirect
POST http://localhost:8080/api/channels
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=01AED759216BCA55B703E52FCC35CEDE

{
  "name": "",
  "date": "2024-03-11",
  "subscribers": 345
}

###API: Update channel
# @no-redirect
PATCH http://localhost:8080/api/channels/1
Content-Type: application/json
Cookie:JSESSIONID=01AED759216BCA55B703E52FCC35CEDE

{
  "name": "Channel",
  "subscribers": 654
}

### API: retrieve one channels (path variable)

GET http://localhost:8080/api/channels/1
Accept: application/xml
Cookie:JSESSIONID=01AED759216BCA55B703E52FCC35CEDE

### API: create user
# @no-redirect
POST http://localhost:8080/api/signup/
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=477C538261DF1DA067B682853CADE6E7
X-CSRF-TOKEN:34y3_w8sfpsvDIXHobvQt8bxigVPtBFXVgIe1TekaPGkQgpB6byEzD8aSvkCOrzyw5bkgfKVp2R81iV6NzMt4QaQWsiQdDwi

{
  "username": "anna",
  "password": "123456"
}