###Homepage
GET http://localhost:8080

###API: retrieve 1 channel
GET http://localhost:8080/api/channels/1
Accept: application/json
Content-Type: application/json

###API: retrieve 1 channel (not found)
GET http://localhost:8080/api/channels/90
Accept: application/json
Content-Type: application/json

### API: delete a channel
DELETE http://localhost:8080/api/channels/2

### API: delete a channel (not found)
DELETE http://localhost:8080/api/channels/90

###API: retrieve videos of a channel
GET http://localhost:8080/api/channels/1/videos

###API: Creating channel
# @no-redirect
POST http://localhost:8080/api/channels
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=01AED759216BCA55B703E52FCC35CEDE

{
  "name": "The name",
  "date": "2024-03-11",
  "subscribers": 345
}

###API: Creating channel (bad request)
# @no-redirect
POST http://localhost:8080/api/channels
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=01AED759216BCA55B703E52FCC35CEDE

{
  "name": "",
  "date": "2024-03-11",
  "subscribers": 345
}

###API: Update channel
# @no-redirect
PATCH http://localhost:8080/api/channels/1
Content-Type: application/json
Cookie:JSESSIONID=01AED759216BCA55B703E52FCC35CEDE

{
  "name": "Channel",
  "subscribers": 654
}

### API: retrieve one channels (path variable)

GET http://localhost:8080/api/channels/1
Accept: application/xml
Cookie:JSESSIONID=01AED759216BCA55B703E52FCC35CEDE
